### PR TITLE
Added support for NUnit2.

### PR DESCRIPTION
**Pull request by ljchristinson**
Renamed the exisiting NUnit3 folder to NUnit3Adapter.
Added the NUnit2 TestAdapter nuget package.
Added the NUnit2Adapter and set the file links to copy the needed dll's there.
Updated changelog.

### CODE REVIEW

**Comment by axodox** [comment]
Great. I will try to review & release it on Sunday.

**Comment by axodox** [comment]
Despite the issues with the vanilla test adapter mentioned in the review I will still merge this, as the support will be enough for most people, and that is better than no support. People using the fancy features might go with V3 anyway.

**Comment by ljchristinson** [comment]
Great, thanks! I agree people should really be using NUnit3 at this point rather than V2.

**Comment by axodox** [comment]
OK, I will do some final touches in a local branch, before putting to master.

**Pull request merged**
